POST https://case-amaro-shaw.herokuapp.com/user/signup
Content-Type: application/json

{
    "userName": "Manuela",
    "password": "123456",
    "email": "manu@bol.com",
    "role": "NORMAL"
}

### 
POST https://case-amaro-shaw.herokuapp.com/user/login
Content-Type: application/json

{ 
    "email": "manu@bol.com",
    "password": "123456"
}

### 
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjczZmU1NjA2LTUxNWEtNDkwMS05MDAwLTZhNGQ4ZTg1MGE4ZCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTgyOTczODYsImV4cCI6MTY1ODMwMDk4Nn0.6n1ln_6kNeNBflSoFxlcZhezQ24xSXEilfUYiE4d74I
POST https://case-amaro-shaw.herokuapp.com/product/addproduct
authorization: {{adminToken}}
Content-Type: application/json

{
    "productName": "Macacão",
    "tags": ["Jeans", "Verão", "Calor"]
}

### 
GET https://case-amaro-shaw.herokuapp.com/product/getproducts
authorization: {{adminToken}}
Content-Type: application/json

{
    "productTag": "jeans"
}

###  
GET https://case-amaro-shaw.herokuapp.com/product/getproducts
authorization: {{adminToken}}
Content-Type: application/json

{
    "productId": "b1910032-daf2-4ebd-b792-2508b1ba3e51"
}

###  
GET https://case-amaro-shaw.herokuapp.com/product/getproducts
authorization: {{adminToken}}
Content-Type: application/json

{
    "productName": "camiseta"
}