POST https://case-amaro-shaw.herokuapp.com/user/signup
Content-Type: application/json

{
    "userName": "Manuela",
    "password": "123456",
    "email": "manu@bol.com",
    "role": "NORMAL"
}

### 
POST https://case-amaro-shaw.herokuapp.com/user/login
Content-Type: application/json

{ 
    "email": "manu@bol.com",
    "password": "123456"
}

### 
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjczZmU1NjA2LTUxNWEtNDkwMS05MDAwLTZhNGQ4ZTg1MGE4ZCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTgzNDUwODMsImV4cCI6MTY1ODM0ODY4M30.DXbfOPKNaSQ8gS5cWuPMqYfyieRyOioYiaerexGwdKg
POST https://case-amaro-shaw.herokuapp.com/product/addproduct
authorization: {{adminToken}}
Content-Type: application/json

{
    "productName": "Macacão",
    "tags": ["Jeans", "Verão", "Calor"]
}

### 
GET https://case-amaro-shaw.herokuapp.com/product/getproducts
authorization: {{adminToken}}
Content-Type: application/json

{
    "productTag": "jeans"
}

###  
GET https://case-amaro-shaw.herokuapp.com/product/getproducts
authorization: {{adminToken}}
Content-Type: application/json

{
    "productId": "60bb17e7-d3c9-4fd7-9bab-8ef63bd62316"
}

###  
GET https://case-amaro-shaw.herokuapp.com/product/getproducts
authorization: {{adminToken}}
Content-Type: application/json

{
    "productName": "camiseta"
}