@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3MDFhMWY1LTNlYTgtNDc1Ny1hZTc1LWQ0OTc2YzJjY2ExZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NjcwNjQzNCwiZXhwIjoxNjU2NzEwMDM0fQ.stLnvwPuOKz5s6QA2U01HNn-SrDEkC7Yl7M5snMGcao

### USER SIGN UP
POST https://cookenu-shaw.herokuapp.com/user/signup
Content-Type: application/json

{
   "name": "Joao",
   "email": "joao@gmail.com",
   "password": "123456",
   "role": "NORMAL"
}

### USER LOGIN
POST https://cookenu-shaw.herokuapp.com/user/login
Content-Type: application/json

{
   "email": "maya01@gmail.com",
   "password": "123456"
}

### GET USER BY TOKEN
# @name getProfile
GET https://cookenu-shaw.herokuapp.com/user/profile
Authorization: {{token2}}

### GET USER BY ID
GET https://cookenu-shaw.herokuapp.com/user/{{getProfile.response.body.id}}
Authorization: {{token2}}

### CREATE RECIPE
POST https://cookenu-shaw.herokuapp.com/user/create/recipe
Authorization: {{token2}}
Content-Type: application/json

{
   "title": "Torta de ameixa seca!",
   "description": "Minha segunda receita."
}

### GET RECIPE BY ID 
GET https://cookenu-shaw.herokuapp.com/recipe/091a94af-3702-43be-a38a-0fe281df31c6
Authorization: {{token2}}

### GET RECIPES FEED OF FOLLOWEDS
GET https://cookenu-shaw.herokuapp.com/feed/recipes
Authorization: {{token2}}

### FOLLOW USER
POST https://cookenu-shaw.herokuapp.com/follow/user
Authorization: {{token2}}
Content-Type: application/json

{
   "userToFollowId": "609a8d40-4158-450b-9224-a215cc9761db"
}

### UNFOLLOW USER
DELETE https://cookenu-shaw.herokuapp.com/unfollow/user
Authorization: {{token2}}
Content-Type: application/json

{
   "userToUnfollowId": "609a8d40-4158-450b-9224-a215cc9761db"
}

### EDIT RECIPE
PUT https://cookenu-shaw.herokuapp.com/edit/recipe/091a94af-3702-43be-a38a-0fe281df31c6
Authorization: {{token2}}
Content-Type: application/json

{
   "title": "Torta de mamão",
   "description": "Mamao e leite condensado e deu!"
}

### DELETE RECIPE
DELETE https://cookenu-shaw.herokuapp.com/delete/recipe/091a94af-3702-43be-a38a-0fe281df31c6
Authorization: {{token2}}

### DELETE USER
DELETE https://cookenu-shaw.herokuapp.com/delete/user/c8a26b21-c0f2-4dc3-9963-6d55aa2caf26
Authorization: {{token2}}

