POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "jobinas@jobs.job",
    "password": "jobina"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "jobs@jobs.job",
    "password": "jobina"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4NzRmZGVlLWZiNGEtNDA3MC1iZDdkLWE3ZGZiNDhlMGQ4NCIsImlhdCI6MTY1NjM1ODM5NSwiZXhwIjoxNjU2MzY1NTk1fQ.ZyEJd7E604CvsxQBoXlUid7PQB2_0zU9UFVjZGL9gaU
GET http://localhost:3003/user/profile
Authorization: {{token}}
