POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "josssssjotoddy@gmail.com",
    "password": "jobina",
    "role": "ADMIN"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "jojotoddy@gmail.com",
    "password": "jobina"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzBiZjU5LTExNTgtNGM3My05ZjVmLWZjMjFhMTM4ODUxNyIsImlhdCI6MTY1NjQyMzc5OSwiZXhwIjoxNjU2NDMwOTk5fQ.ruTiWjzAcbn8BNJ_CIuqjkDFUhrQ7FmPR2Q03yNmOoA
GET http://localhost:3003/user/profile
Authorization: {{token}}
